module.exports = {
  projects: [
    '<rootDir>/apps/api',
    '<rootDir>/libs/api/user',
    '<rootDir>/libs/api/database',
    '<rootDir>/libs/api/auth',
    '<rootDir>/apps/finance',
    '<rootDir>/apps/finance-web',
    '<rootDir>/libs/frontend/core',
    '<rootDir>/libs/core',
    '<rootDir>/libs/frontend/core/core',
    '<rootDir>/libs/frontend/finance',
    '<rootDir>/libs/frontend/ui',
    '<rootDir>/libs/api/shared',
    '<rootDir>/libs/api/modules',
    '<rootDir>/libs/mobile/core',
    '<rootDir>/libs/mobile/shared',
    '<rootDir>/libs/style',
    '<rootDir>/libs/client/shared',
  ],
};
